name: grillhouse
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_api: <1.0.0
  amplify_auth_cognito: <1.0.0
  amplify_datastore: <1.0.0
  amplify_flutter: <1.0.0
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.0
  flutter_config: ^1.0.8
  flutter_launcher_icons: ^0.8.1
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.1
  fluttertoast: ^7.1.8
  google_nav_bar: ^4.0.2
  http: ^0.12.2
  badges: ^1.2.0
  progress_dialog: ^1.2.4
  provider: ^4.1.0
  razorpay_flutter: ^1.2.5
  shared_preferences: ^2.0.5
  webview_flutter: ^1.0.7
  intl: ^0.16.1
  lottie: '0.7.0+1'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
        - asset: fonts/OpenSans/OpenSans-Italic.ttf
          weight: 700
  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
